/**
 * editorial-personalizer.ts
 *
 * Per-contact personalized block injection for editorial newsletter sends.
 *
 * Two public exports:
 *   generatePersonalizedBlock(ctx)         → Promise<string>  HTML snippet or ''
 *   injectPersonalizedBlock(html, snippet) → string           HTML with marker replaced
 *
 * The marker <!-- __PERSONALIZED_BLOCK__ --> is placed in the rendered email HTML
 * (by editorial-renderer.tsx) and replaced here with a per-contact italic pull-quote
 * paragraph generated by Claude Haiku.
 */

import Anthropic from '@anthropic-ai/sdk';

// ── Marker ────────────────────────────────────────────────────────────────────

/** Injection point placed by the email renderer, replaced per-contact at send time. */
export const PERSONALIZED_BLOCK_MARKER = '<!-- __PERSONALIZED_BLOCK__ -->';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ContactIntelligence {
  engagement_score?: number;
  inferred_interests?: {
    areas?: string[];
    property_types?: string[];
    lifestyle_tags?: string[];
  };
  click_history?: Array<{ link_type?: string; clicked_at?: string }>;
  last_clicked?: string;
}

export interface LeadScore {
  intent?: string;           // e.g. "serious_buyer", "considering_selling", "investor"
  buying_readiness?: number; // 0-100
  personalization_hints?: {
    hot_topic?: string;
    price_anchor?: string;
    relationship_stage?: string;
  };
}

export interface PersonalizationContext {
  contactName: string | null;
  notes: string | null;
  intelligence: ContactIntelligence | null;
  leadScore: LeadScore | null;
  editionType: string; // e.g. "market_update"
}

// ── Anthropic client (lazy singleton) ────────────────────────────────────────

let _client: Anthropic | null = null;
function getClient(): Anthropic {
  if (!_client) {
    _client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  }
  return _client;
}

// ── HTML wrapper for the personalized paragraph ────────────────────────────

function wrapInBlock(text: string): string {
  // Inline table-row structure compatible with email clients (inbox-safe)
  return [
    '<tr><td style="padding:0 40px 24px">',
    '  <p style="font-family:Georgia,\'Times New Roman\',serif;font-size:15px;color:#4a4a3a;',
    'margin:0;line-height:1.75;font-style:italic;border-left:3px solid #c9a96e;',
    'padding-left:16px">',
    text,
    '  </p>',
    '</td></tr>',
  ].join('');
}

// ── generatePersonalizedBlock ─────────────────────────────────────────────────

/**
 * Calls Claude Haiku to produce a 2-4 sentence personalised paragraph for
 * this contact based on their intelligence profile. Returns an HTML string
 * ready for injection, or '' if:
 *   - The model returns "SKIP" (no useful signals)
 *   - The response is empty
 *   - Any error occurs (best-effort, never throws)
 */
export async function generatePersonalizedBlock(
  ctx: PersonalizationContext,
): Promise<string> {
  try {
    // Determine most recent intent signal from click history
    const recentIntent = (() => {
      const clicks = ctx.intelligence?.click_history;
      if (!clicks || clicks.length === 0) return 'none';
      // Sort by date descending, take the most recent link_type
      const sorted = [...clicks]
        .filter((c) => c.clicked_at)
        .sort((a, b) =>
          (b.clicked_at ?? '').localeCompare(a.clicked_at ?? ''),
        );
      return sorted[0]?.link_type ?? 'none';
    })();

    const prompt = `You are writing a single short personalized paragraph (2-4 sentences max) to insert into a real estate newsletter email. Match the editorial tone — professional, warm, data-grounded. Do NOT use placeholder text. Do NOT start with "Hi" or the contact's name.

Contact profile:
- Name: ${ctx.contactName || 'this reader'}
- Inferred interests: ${JSON.stringify(ctx.intelligence?.inferred_interests || {})}
- Recent click intent: ${recentIntent}
- Lead score intent: ${ctx.leadScore?.intent || 'unknown'}
- Buying readiness: ${ctx.leadScore?.buying_readiness ?? 'unknown'}/100
- Hot topic: ${ctx.leadScore?.personalization_hints?.hot_topic || 'none'}
- Realtor notes: ${ctx.notes || 'none'}

Edition type: ${ctx.editionType}

Write one paragraph (no HTML tags, plain text only) that feels personally relevant to this reader based on their profile. If no useful signals exist, return exactly: SKIP`;

    const response = await getClient().messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 200,
      messages: [{ role: 'user', content: prompt }],
    });

    const raw =
      response.content[0]?.type === 'text' ? response.content[0].text.trim() : '';

    if (!raw || raw === 'SKIP' || raw.toUpperCase().startsWith('SKIP')) {
      return '';
    }

    // Strip any stray HTML tags the model may have produced despite the instruction
    const clean = raw.replace(/<[^>]*>/g, '').trim();
    if (!clean) return '';

    return wrapInBlock(clean);
  } catch {
    // Never propagate — personalization is best-effort
    return '';
  }
}

// ── injectPersonalizedBlock ───────────────────────────────────────────────────

/**
 * Replaces the PERSONALIZED_BLOCK_MARKER in `html` with `blockHtml`.
 * If blockHtml is empty the marker is simply removed.
 * If the marker is not found the HTML is returned unchanged.
 */
export function injectPersonalizedBlock(html: string, blockHtml: string): string {
  if (!html.includes(PERSONALIZED_BLOCK_MARKER)) return html;
  return html.replace(PERSONALIZED_BLOCK_MARKER, blockHtml);
}
