/**
 * HMAC-signed unsubscribe tokens.
 *
 * P0 SECURITY: Before this, unsubscribe links used plain contact IDs
 * (?id=<uuid>). Anyone could enumerate UUIDs and unsubscribe arbitrary
 * contacts. Now the link includes an HMAC signature that proves the
 * token was generated by our server.
 *
 * Format: ?token=<contactId>.<hmac>
 * The HMAC is a SHA-256 hash of the contactId using NEXTAUTH_SECRET
 * as the key (reusing the existing secret to avoid adding a new env var).
 */

import { createHmac } from "node:crypto";

const SECRET = process.env.NEXTAUTH_SECRET || "";

/**
 * Generate a signed unsubscribe token for a contact.
 */
export function generateUnsubscribeToken(contactId: string): string {
  const hmac = createHmac("sha256", SECRET)
    .update(contactId)
    .digest("hex")
    .slice(0, 16); // 16 hex chars = 64 bits, sufficient for anti-enumeration
  return `${contactId}.${hmac}`;
}

/**
 * Verify an unsubscribe token. Returns the contactId if valid, null if not.
 */
export function verifyUnsubscribeToken(token: string): string | null {
  const parts = token.split(".");
  if (parts.length !== 2) return null;

  const [contactId, providedHmac] = parts;
  if (!contactId || !providedHmac) return null;

  const expectedHmac = createHmac("sha256", SECRET)
    .update(contactId)
    .digest("hex")
    .slice(0, 16);

  // Constant-time comparison to prevent timing attacks
  if (providedHmac.length !== expectedHmac.length) return null;

  let mismatch = 0;
  for (let i = 0; i < providedHmac.length; i++) {
    mismatch |= providedHmac.charCodeAt(i) ^ expectedHmac.charCodeAt(i);
  }

  return mismatch === 0 ? contactId : null;
}

/**
 * Build the full unsubscribe URL for use in email footers.
 */
export function buildUnsubscribeUrl(contactId: string): string {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://realtors360.ai";
  const token = generateUnsubscribeToken(contactId);
  return `${baseUrl}/api/newsletters/unsubscribe?token=${token}`;
}
