'use client'

import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import type {
  EditorBlock,
  EditorBlockContent,
  HeroBlockContent,
  JustSoldBlockContent,
  MarketCommentaryBlockContent,
  RateWatchBlockContent,
  LocalIntelBlockContent,
  NeighborhoodSpotlightBlockContent,
  QuickTipBlockContent,
  AgentNoteBlockContent,
  CtaBlockContent,
  DividerBlockContent,
} from '@/types/editorial'

// ── Shared helpers ────────────────────────────────────────────────────────────

function FieldGroup({ children, className }: { children: React.ReactNode; className?: string }) {
  return <div className={['flex flex-col gap-1.5', className].filter(Boolean).join(' ')}>{children}</div>
}

function CharCount({ value, max }: { value: string | null | undefined; max: number }) {
  const len = value?.length ?? 0
  const over = len > max
  return (
    <span className={['text-xs tabular-nums', over ? 'text-destructive font-medium' : 'text-muted-foreground'].join(' ')}>
      {len}/{max}
    </span>
  )
}

function WordCount({ value }: { value: string | null | undefined }) {
  const words = value?.trim() ? value.trim().split(/\s+/).length : 0
  return (
    <span className="text-xs text-muted-foreground tabular-nums">{words} words</span>
  )
}

interface LockBannerProps {
  isLocked: boolean
  isAiGenerated: boolean
  onToggleLock: () => void
  disabled: boolean
}

function LockBanner({ isLocked, isAiGenerated, onToggleLock, disabled }: LockBannerProps) {
  if (isLocked) {
    return (
      <div className="flex items-center justify-between rounded-lg bg-[#f5c26b]/10 border border-[#f5c26b]/30 px-3 py-2 mb-4">
        <div className="flex items-center gap-2">
          <Badge variant="warning" className="text-xs">✏️ Manually edited</Badge>
          <span className="text-xs text-muted-foreground">Won&apos;t be regenerated by AI</span>
        </div>
        <Button
          variant="ghost"
          size="xs"
          onClick={onToggleLock}
          disabled={disabled}
          aria-label="Unlock this block for AI regeneration"
        >
          🔓 Unlock
        </Button>
      </div>
    )
  }

  if (isAiGenerated) {
    return (
      <div className="flex items-center justify-between rounded-lg bg-muted/40 border border-border px-3 py-2 mb-4">
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">🤖 AI generated</span>
        </div>
        <Button
          variant="ghost"
          size="xs"
          onClick={onToggleLock}
          disabled={disabled}
          aria-label="Lock this block to prevent AI from overwriting your edits"
        >
          🔒 Lock edits
        </Button>
      </div>
    )
  }

  return (
    <div className="flex items-center justify-end mb-4">
      <Button
        variant="ghost"
        size="xs"
        onClick={onToggleLock}
        disabled={disabled}
        aria-label="Lock this block to prevent AI from overwriting your edits"
      >
        🔒 Lock edits
      </Button>
    </div>
  )
}

// ── Per-type editors ──────────────────────────────────────────────────────────

function HeroEditor({
  content,
  onChange,
  disabled,
}: {
  content: HeroBlockContent
  onChange: (update: Partial<HeroBlockContent>) => void
  disabled: boolean
}) {
  return (
    <div className="flex flex-col gap-4">
      <FieldGroup>
        <div className="flex items-center justify-between">
          <Label htmlFor="hero-headline">Headline *</Label>
          <CharCount value={content.headline} max={80} />
        </div>
        <Input
          id="hero-headline"
          value={content.headline ?? ''}
          maxLength={80}
          placeholder="e.g. Spring market heats up in Kitsilano"
          onChange={(e) => onChange({ headline: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <div className="flex items-center justify-between">
          <Label htmlFor="hero-subheadline">Subheadline</Label>
          <CharCount value={content.subheadline} max={120} />
        </div>
        <Input
          id="hero-subheadline"
          value={content.subheadline ?? ''}
          maxLength={120}
          placeholder="e.g. What the latest sales data means for buyers and sellers"
          onChange={(e) => onChange({ subheadline: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="hero-image">Hero Image URL</Label>
        <Input
          id="hero-image"
          type="url"
          value={content.image_url ?? ''}
          placeholder="https://..."
          onChange={(e) => onChange({ image_url: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="hero-edition">Edition Label</Label>
        <Input
          id="hero-edition"
          value={content.edition_label ?? ''}
          placeholder="e.g. #42"
          onChange={(e) => onChange({ edition_label: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>
    </div>
  )
}

function JustSoldEditor({
  content,
  onChange,
  disabled,
  onLoadTransaction,
}: {
  content: JustSoldBlockContent
  onChange: (update: Partial<JustSoldBlockContent>) => void
  disabled: boolean
  onLoadTransaction?: () => Promise<void>
}) {
  const [loadingTx, setLoadingTx] = React.useState(false)

  async function handleLoadTransaction() {
    if (!onLoadTransaction) return
    setLoadingTx(true)
    try {
      await onLoadTransaction()
    } finally {
      setLoadingTx(false)
    }
  }

  return (
    <div className="flex flex-col gap-4">
      {onLoadTransaction && (
        <div className="mb-2">
          <button
            type="button"
            onClick={handleLoadTransaction}
            disabled={disabled || loadingTx}
            style={{
              fontSize: 13,
              color: '#FF7A59',
              background: 'none',
              border: '1px solid #FF7A59',
              borderRadius: 6,
              padding: '4px 12px',
              cursor: disabled || loadingTx ? 'not-allowed' : 'pointer',
              opacity: disabled || loadingTx ? 0.6 : 1,
            }}
          >
            {loadingTx ? '⏳ Loading…' : '📥 Load from my transactions'}
          </button>
        </div>
      )}
      <FieldGroup>
        <Label htmlFor="js-address">Address *</Label>
        <Input
          id="js-address"
          value={content.address ?? ''}
          placeholder="e.g. 123 Main St, Vancouver, BC"
          onChange={(e) => onChange({ address: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <div className="grid grid-cols-2 gap-3">
        <FieldGroup>
          <Label htmlFor="js-sale-price">Sale Price *</Label>
          <Input
            id="js-sale-price"
            type="number"
            value={content.sale_price ?? ''}
            placeholder="1250000"
            onChange={(e) => onChange({ sale_price: parseFloat(e.target.value) || 0 })}
            disabled={disabled}
          />
        </FieldGroup>
        <FieldGroup>
          <Label htmlFor="js-list-price">List Price</Label>
          <Input
            id="js-list-price"
            type="number"
            value={content.list_price ?? ''}
            placeholder="1199000"
            onChange={(e) => onChange({ list_price: parseFloat(e.target.value) || 0 })}
            disabled={disabled}
          />
        </FieldGroup>
      </div>

      <FieldGroup>
        <Label htmlFor="js-dom">Days on Market</Label>
        <Input
          id="js-dom"
          type="number"
          min={0}
          value={content.days_on_market ?? ''}
          placeholder="7"
          onChange={(e) => onChange({ days_on_market: parseInt(e.target.value, 10) || 0 })}
          disabled={disabled}
        />
      </FieldGroup>

      <div className="grid grid-cols-3 gap-3">
        <FieldGroup>
          <Label htmlFor="js-beds">Beds</Label>
          <Input
            id="js-beds"
            type="number"
            min={0}
            value={content.beds ?? ''}
            placeholder="3"
            onChange={(e) => onChange({ beds: parseInt(e.target.value, 10) || null })}
            disabled={disabled}
          />
        </FieldGroup>
        <FieldGroup>
          <Label htmlFor="js-baths">Baths</Label>
          <Input
            id="js-baths"
            type="number"
            min={0}
            step={0.5}
            value={content.baths ?? ''}
            placeholder="2"
            onChange={(e) => onChange({ baths: parseFloat(e.target.value) || null })}
            disabled={disabled}
          />
        </FieldGroup>
        <FieldGroup>
          <Label htmlFor="js-sqft">Sq Ft</Label>
          <Input
            id="js-sqft"
            type="number"
            min={0}
            value={content.sqft ?? ''}
            placeholder="1400"
            onChange={(e) => onChange({ sqft: parseInt(e.target.value, 10) || null })}
            disabled={disabled}
          />
        </FieldGroup>
      </div>

      <FieldGroup>
        <Label htmlFor="js-commentary">Commentary</Label>
        <Textarea
          id="js-commentary"
          value={content.commentary ?? ''}
          rows={3}
          placeholder="A brief note about this sale..."
          onChange={(e) => onChange({ commentary: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>
    </div>
  )
}

function MarketCommentaryEditor({
  content,
  onChange,
  disabled,
}: {
  content: MarketCommentaryBlockContent
  onChange: (update: Partial<MarketCommentaryBlockContent>) => void
  disabled: boolean
}) {
  return (
    <div className="flex flex-col gap-4">
      <FieldGroup>
        <Label htmlFor="mc-neighbourhood">Neighbourhood *</Label>
        <Input
          id="mc-neighbourhood"
          value={content.neighbourhood ?? ''}
          placeholder="e.g. Kitsilano"
          onChange={(e) => onChange({ neighbourhood: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <div className="flex items-center justify-between">
          <Label htmlFor="mc-body">Commentary *</Label>
          <div className="flex items-center gap-2">
            <WordCount value={content.body} />
            <CharCount value={content.body} max={500} />
          </div>
        </div>
        <Textarea
          id="mc-body"
          value={content.body ?? ''}
          rows={6}
          maxLength={500}
          placeholder="Write your market commentary (min 80 characters)..."
          onChange={(e) => onChange({ body: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <div className="grid grid-cols-2 gap-3">
        <FieldGroup>
          <Label htmlFor="mc-stat1-label">Stat 1 Label</Label>
          <Input
            id="mc-stat1-label"
            value={content.period_label ?? ''}
            placeholder="e.g. Avg. Sale Price"
            onChange={(e) => onChange({ period_label: e.target.value || null })}
            disabled={disabled}
          />
        </FieldGroup>
        <FieldGroup>
          <Label htmlFor="mc-stat1-value">Stat 1 Value</Label>
          <Input
            id="mc-stat1-value"
            type="number"
            value={content.avg_sale_price ?? ''}
            placeholder="e.g. 1250000"
            onChange={(e) => onChange({ avg_sale_price: parseFloat(e.target.value) || null })}
            disabled={disabled}
          />
        </FieldGroup>

        <FieldGroup>
          <Label htmlFor="mc-stat2-label">Stat 2 Label</Label>
          <Input
            id="mc-stat2-label"
            value={'Median DOM'}
            placeholder="e.g. Median DOM"
            disabled
          />
        </FieldGroup>
        <FieldGroup>
          <Label htmlFor="mc-stat2-value">Stat 2 Value</Label>
          <Input
            id="mc-stat2-value"
            type="number"
            value={content.median_dom ?? ''}
            placeholder="e.g. 12"
            onChange={(e) => onChange({ median_dom: parseInt(e.target.value, 10) || null })}
            disabled={disabled}
          />
        </FieldGroup>
      </div>

      <FieldGroup>
        <Label htmlFor="mc-market-type">Market Type</Label>
        <Select
          value={content.market_type ?? ''}
          onValueChange={(val) =>
            onChange({ market_type: val as MarketCommentaryBlockContent['market_type'] })
          }
          disabled={disabled}
        >
          <SelectTrigger id="mc-market-type" className="w-full">
            <SelectValue placeholder="Select market type..." />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="buyers">Buyer&apos;s Market</SelectItem>
            <SelectItem value="sellers">Seller&apos;s Market</SelectItem>
            <SelectItem value="balanced">Balanced Market</SelectItem>
          </SelectContent>
        </Select>
      </FieldGroup>
    </div>
  )
}

function RateWatchEditor({
  content,
  onChange,
  disabled,
}: {
  content: RateWatchBlockContent
  onChange: (update: Partial<RateWatchBlockContent>) => void
  disabled: boolean
}) {
  return (
    <div className="flex flex-col gap-4">
      <FieldGroup>
        <Label htmlFor="rw-commentary">Commentary</Label>
        <Textarea
          id="rw-commentary"
          value={content.commentary ?? ''}
          rows={3}
          placeholder="e.g. The Bank of Canada held rates steady this month..."
          onChange={(e) => onChange({ commentary: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>

      <div className="grid grid-cols-2 gap-3">
        <FieldGroup>
          <Label htmlFor="rw-1yr">1-Year Fixed (%)</Label>
          <Input
            id="rw-1yr"
            type="number"
            step="0.01"
            value={content.rate_1yr_fixed ?? ''}
            placeholder="e.g. 5.49"
            onChange={(e) => onChange({ rate_1yr_fixed: parseFloat(e.target.value) || null })}
            disabled={disabled}
          />
        </FieldGroup>

        <FieldGroup>
          <Label htmlFor="rw-3yr">3-Year Fixed (%)</Label>
          <Input
            id="rw-3yr"
            type="number"
            step="0.01"
            value={content.rate_3yr_fixed ?? ''}
            placeholder="e.g. 5.19"
            onChange={(e) => onChange({ rate_3yr_fixed: parseFloat(e.target.value) || null })}
            disabled={disabled}
          />
        </FieldGroup>

        <FieldGroup>
          <Label htmlFor="rw-5yr">5-Year Fixed (%)</Label>
          <Input
            id="rw-5yr"
            type="number"
            step="0.01"
            value={content.rate_5yr_fixed ?? ''}
            placeholder="e.g. 4.89"
            onChange={(e) => onChange({ rate_5yr_fixed: parseFloat(e.target.value) || null })}
            disabled={disabled}
          />
        </FieldGroup>

        <FieldGroup>
          <Label htmlFor="rw-variable">5-Year Variable (%)</Label>
          <Input
            id="rw-variable"
            type="number"
            step="0.01"
            value={content.rate_5yr_variable ?? ''}
            placeholder="e.g. 5.95"
            onChange={(e) => onChange({ rate_5yr_variable: parseFloat(e.target.value) || null })}
            disabled={disabled}
          />
        </FieldGroup>
      </div>

      <FieldGroup>
        <Label htmlFor="rw-trend">Rate Trend</Label>
        <Select
          value={content.trend ?? ''}
          onValueChange={(val) => onChange({ trend: val as RateWatchBlockContent['trend'] })}
          disabled={disabled}
        >
          <SelectTrigger id="rw-trend" className="w-full">
            <SelectValue placeholder="Select trend..." />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="rising">Rising ↑</SelectItem>
            <SelectItem value="falling">Falling ↓</SelectItem>
            <SelectItem value="stable">Stable →</SelectItem>
          </SelectContent>
        </Select>
      </FieldGroup>
    </div>
  )
}

function LocalIntelEditor({
  content,
  onChange,
  disabled,
}: {
  content: LocalIntelBlockContent
  onChange: (update: Partial<LocalIntelBlockContent>) => void
  disabled: boolean
}) {
  return (
    <div className="flex flex-col gap-4">
      <FieldGroup>
        <Label htmlFor="li-headline">Headline *</Label>
        <Input
          id="li-headline"
          value={content.headline ?? ''}
          placeholder="e.g. New SkyTrain extension approved for Surrey"
          onChange={(e) => onChange({ headline: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="li-body">News Item *</Label>
        <Textarea
          id="li-body"
          value={content.body ?? ''}
          rows={4}
          placeholder="Summarise the local news story and what it means for the market..."
          onChange={(e) => onChange({ body: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="li-category">Category</Label>
        <Select
          value={content.category ?? 'other'}
          onValueChange={(val) => onChange({ category: val as LocalIntelBlockContent['category'] })}
          disabled={disabled}
        >
          <SelectTrigger id="li-category" className="w-full">
            <SelectValue placeholder="Select category..." />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="development">Development</SelectItem>
            <SelectItem value="transit">Transit</SelectItem>
            <SelectItem value="school">School</SelectItem>
            <SelectItem value="business">Business</SelectItem>
            <SelectItem value="zoning">Zoning</SelectItem>
            <SelectItem value="event">Event</SelectItem>
            <SelectItem value="other">Other</SelectItem>
          </SelectContent>
        </Select>
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="li-source">Source URL</Label>
        <Input
          id="li-source"
          type="url"
          value={content.source_url ?? ''}
          placeholder="https://..."
          onChange={(e) => onChange({ source_url: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>
    </div>
  )
}

function NeighborhoodSpotlightEditor({
  content,
  onChange,
  disabled,
}: {
  content: NeighborhoodSpotlightBlockContent
  onChange: (update: Partial<NeighborhoodSpotlightBlockContent>) => void
  disabled: boolean
}) {
  const highlights = content.highlights ?? ['', '', '']

  function updateHighlight(index: number, value: string) {
    const next = [...highlights]
    next[index] = value
    onChange({ highlights: next })
  }

  return (
    <div className="flex flex-col gap-4">
      <FieldGroup>
        <Label htmlFor="ns-neighbourhood">Neighbourhood *</Label>
        <Input
          id="ns-neighbourhood"
          value={content.neighbourhood ?? ''}
          placeholder="e.g. Mount Pleasant"
          onChange={(e) => onChange({ neighbourhood: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="ns-tagline">Tagline</Label>
        <Input
          id="ns-tagline"
          value={content.tagline ?? ''}
          placeholder="e.g. Where art meets urban living"
          onChange={(e) => onChange({ tagline: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="ns-description">Description</Label>
        <Textarea
          id="ns-description"
          value={content.description ?? ''}
          rows={4}
          placeholder="Describe the neighbourhood's character, vibe, and lifestyle..."
          onChange={(e) => onChange({ description: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <div className="flex flex-col gap-2">
        <Label>Highlights (up to 3)</Label>
        {[0, 1, 2].map((i) => (
          <Input
            key={i}
            value={highlights[i] ?? ''}
            placeholder={`Highlight ${i + 1}, e.g. "Excellent walkability (93/100)"`}
            onChange={(e) => updateHighlight(i, e.target.value)}
            disabled={disabled}
          />
        ))}
      </div>
    </div>
  )
}

function QuickTipEditor({
  content,
  onChange,
  disabled,
}: {
  content: QuickTipBlockContent
  onChange: (update: Partial<QuickTipBlockContent>) => void
  disabled: boolean
}) {
  return (
    <div className="flex flex-col gap-4">
      <FieldGroup>
        <Label htmlFor="qt-title">Tip Title *</Label>
        <Input
          id="qt-title"
          value={content.title ?? ''}
          placeholder="e.g. Time your sale before summer slowdown"
          onChange={(e) => onChange({ title: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <div className="flex items-center justify-between">
          <Label htmlFor="qt-body">Tip Body *</Label>
          <CharCount value={content.body} max={300} />
        </div>
        <Textarea
          id="qt-body"
          value={content.body ?? ''}
          rows={3}
          maxLength={300}
          placeholder="Expand on the tip in 2-4 sentences..."
          onChange={(e) => onChange({ body: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="qt-category">Category</Label>
        <Select
          value={content.category ?? 'general'}
          onValueChange={(val) => onChange({ category: val as QuickTipBlockContent['category'] })}
          disabled={disabled}
        >
          <SelectTrigger id="qt-category" className="w-full">
            <SelectValue placeholder="Select category..." />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="buying">Buying</SelectItem>
            <SelectItem value="selling">Selling</SelectItem>
            <SelectItem value="investing">Investing</SelectItem>
            <SelectItem value="maintenance">Maintenance</SelectItem>
            <SelectItem value="financing">Financing</SelectItem>
            <SelectItem value="staging">Staging</SelectItem>
            <SelectItem value="general">General</SelectItem>
          </SelectContent>
        </Select>
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="qt-icon">Icon Emoji</Label>
        <Input
          id="qt-icon"
          value={content.icon_emoji ?? ''}
          placeholder="e.g. 💡"
          onChange={(e) => onChange({ icon_emoji: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>
    </div>
  )
}

function AgentNoteEditor({
  content,
  onChange,
  disabled,
}: {
  content: AgentNoteBlockContent
  onChange: (update: Partial<AgentNoteBlockContent>) => void
  disabled: boolean
}) {
  return (
    <div className="flex flex-col gap-4">
      <FieldGroup>
        <div className="flex items-center justify-between">
          <Label htmlFor="an-note">Note *</Label>
          <CharCount value={content.body} max={500} />
        </div>
        <Textarea
          id="an-note"
          value={content.body ?? ''}
          rows={4}
          maxLength={500}
          placeholder="Write your personal note to readers..."
          onChange={(e) => onChange({ body: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="an-sign-off">Sign-off</Label>
        <Input
          id="an-sign-off"
          value={content.sign_off ?? ''}
          placeholder="e.g. Talk soon, — Sarah"
          onChange={(e) => onChange({ sign_off: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="an-agent-name">Agent Name</Label>
        <Input
          id="an-agent-name"
          value={content.agent_name ?? ''}
          placeholder="e.g. Sarah Cho"
          onChange={(e) => onChange({ agent_name: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>
    </div>
  )
}

function CtaEditor({
  content,
  onChange,
  disabled,
}: {
  content: CtaBlockContent
  onChange: (update: Partial<CtaBlockContent>) => void
  disabled: boolean
}) {
  return (
    <div className="flex flex-col gap-4">
      <FieldGroup>
        <div className="flex items-center justify-between">
          <Label htmlFor="cta-headline">Headline</Label>
          <CharCount value={content.headline} max={80} />
        </div>
        <Input
          id="cta-headline"
          value={content.headline ?? ''}
          maxLength={80}
          placeholder="e.g. Ready to make your move?"
          onChange={(e) => onChange({ headline: e.target.value })}
          disabled={disabled}
        />
      </FieldGroup>

      <div className="grid grid-cols-2 gap-3">
        <FieldGroup>
          <div className="flex items-center justify-between">
            <Label htmlFor="cta-button-text">Button Text *</Label>
            <CharCount value={content.button_label} max={30} />
          </div>
          <Input
            id="cta-button-text"
            value={content.button_label ?? ''}
            maxLength={30}
            placeholder="e.g. Book a Call"
            onChange={(e) => onChange({ button_label: e.target.value })}
            disabled={disabled}
          />
        </FieldGroup>

        <FieldGroup>
          <Label htmlFor="cta-button-url">Button URL *</Label>
          <Input
            id="cta-button-url"
            type="url"
            value={content.button_url ?? ''}
            placeholder="https://..."
            onChange={(e) => onChange({ button_url: e.target.value })}
            disabled={disabled}
          />
        </FieldGroup>
      </div>

      <FieldGroup>
        <Label htmlFor="cta-subtext">Subtext</Label>
        <Textarea
          id="cta-subtext"
          value={content.subtext ?? ''}
          rows={2}
          placeholder="Optional supporting copy beneath the button..."
          onChange={(e) => onChange({ subtext: e.target.value || null })}
          disabled={disabled}
        />
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="cta-type">CTA Type</Label>
        <Select
          value={content.cta_type ?? 'custom'}
          onValueChange={(val) => onChange({ cta_type: val as CtaBlockContent['cta_type'] })}
          disabled={disabled}
        >
          <SelectTrigger id="cta-type" className="w-full">
            <SelectValue placeholder="Select CTA type..." />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="book_call">Book a Call</SelectItem>
            <SelectItem value="get_cma">Get a CMA</SelectItem>
            <SelectItem value="view_listings">View Listings</SelectItem>
            <SelectItem value="open_house_rsvp">Open House RSVP</SelectItem>
            <SelectItem value="referral">Referral</SelectItem>
            <SelectItem value="custom">Custom</SelectItem>
          </SelectContent>
        </Select>
      </FieldGroup>

      <FieldGroup>
        <Label htmlFor="cta-style">Style</Label>
        <Select
          value={content.style ?? 'primary'}
          onValueChange={(val) => onChange({ style: val as CtaBlockContent['style'] })}
          disabled={disabled}
        >
          <SelectTrigger id="cta-style" className="w-full">
            <SelectValue placeholder="Select style..." />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="primary">Primary (filled)</SelectItem>
            <SelectItem value="soft">Soft (tinted)</SelectItem>
            <SelectItem value="outlined">Outlined</SelectItem>
          </SelectContent>
        </Select>
      </FieldGroup>
    </div>
  )
}

function DividerEditor() {
  return (
    <div className="flex flex-col items-center gap-4 py-6">
      <p className="text-sm text-muted-foreground text-center">
        No configuration needed for dividers.
      </p>
      <div className="w-full border-t border-border" />
    </div>
  )
}

// ── Main component ────────────────────────────────────────────────────────────

interface BlockEditorProps {
  block: EditorBlock
  onUpdate: (blockId: string, content: Partial<EditorBlockContent>) => void
  onToggleLock: (blockId: string) => void
  isGenerating: boolean
}

export function BlockEditor({ block, onUpdate, onToggleLock, isGenerating }: BlockEditorProps) {
  function handleChange(update: Partial<EditorBlockContent>) {
    onUpdate(block.id, update)
  }

  // Determine if any content has been set (for "AI generated" indicator)
  // We consider it AI-generated if the block has content but is not locked
  const hasContent = (() => {
    const c = block.content as unknown as Record<string, unknown>
    return Object.values(c).some((v) => v !== null && v !== '' && v !== undefined)
  })()

  /** Load the most recent just_sold transaction and auto-populate this block */
  async function handleLoadTransaction() {
    const { listTransactions } = await import('@/actions/editorial')
    const result = await listTransactions()
    if (!result.data || result.data.length === 0) return

    // Prefer a just_sold transaction; fall back to whatever exists
    const tx = result.data.find(t => t.transaction_type === 'just_sold') ?? result.data[0]

    onUpdate(block.id, {
      address: tx.address,
      sale_price: tx.sale_price ? tx.sale_price / 100 : 0,
      list_price: tx.list_price / 100,
      days_on_market: tx.days_on_market ?? 0,
      commentary: tx.story ?? null,
      sold_date: tx.sold_at ?? '',
    } as Partial<EditorBlockContent>)
  }

  return (
    <div className="flex flex-col">
      {/* Lock banner */}
      <LockBanner
        isLocked={block.is_locked}
        isAiGenerated={hasContent && !block.is_locked}
        onToggleLock={() => onToggleLock(block.id)}
        disabled={isGenerating}
      />

      {/* Field editors by type */}
      {block.type === 'hero' && (
        <HeroEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
        />
      )}
      {block.type === 'just_sold' && (
        <JustSoldEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
          onLoadTransaction={handleLoadTransaction}
        />
      )}
      {block.type === 'market_commentary' && (
        <MarketCommentaryEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
        />
      )}
      {block.type === 'rate_watch' && (
        <RateWatchEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
        />
      )}
      {block.type === 'local_intel' && (
        <LocalIntelEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
        />
      )}
      {block.type === 'neighborhood_spotlight' && (
        <NeighborhoodSpotlightEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
        />
      )}
      {block.type === 'quick_tip' && (
        <QuickTipEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
        />
      )}
      {block.type === 'agent_note' && (
        <AgentNoteEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
        />
      )}
      {block.type === 'cta' && (
        <CtaEditor
          content={block.content}
          onChange={(u) => handleChange(u)}
          disabled={isGenerating}
        />
      )}
      {block.type === 'divider' && <DividerEditor />}
    </div>
  )
}
