"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Save, Loader2, Sparkles } from "lucide-react";
import { generateAndSaveMLSRemarks, updateMLSRemarks } from "@/actions/mls-remarks";
import { toast } from "sonner";

const MAX_CHARS = 500;

interface MLSRemarksPanelProps {
  listingId: string;
  publicRemarks: string | null;
  realtorRemarks: string | null;
  onRefresh: () => void;
}

export function MLSRemarksPanel({ listingId, publicRemarks, realtorRemarks, onRefresh }: MLSRemarksPanelProps) {
  const [pub, setPub] = useState(publicRemarks || "");
  const [realtor, setRealtor] = useState(realtorRemarks || "");
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [editing, setEditing] = useState(false);

  const hasChanges = pub !== (publicRemarks || "") || realtor !== (realtorRemarks || "");

  async function handleGenerate() {
    setGenerating(true);
    const result = await generateAndSaveMLSRemarks(listingId);
    setGenerating(false);

    if (result.error) {
      toast.error(result.error);
    } else if (result.remarks) {
      setPub(result.remarks.publicRemarks);
      setRealtor(result.remarks.realtorRemarks);
      toast.success("MLS remarks generated by AI");
      onRefresh();
    }
  }

  async function handleSave() {
    setSaving(true);
    const result = await updateMLSRemarks(listingId, {
      mls_remarks: pub.trim() || undefined,
      mls_realtor_remarks: realtor.trim() || undefined,
    });
    setSaving(false);

    if (result.error) {
      toast.error(result.error);
    } else {
      toast.success("Remarks saved");
      setEditing(false);
      onRefresh();
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm font-semibold">MLS Remarks</p>
        <Button
          variant="outline"
          size="sm"
          onClick={handleGenerate}
          disabled={generating}
          className="gap-1.5 text-xs"
        >
          {generating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Sparkles className="h-3.5 w-3.5" />}
          {generating ? "Generating..." : "AI Generate"}
        </Button>
      </div>

      {/* Public Remarks */}
      <div>
        <div className="flex items-center justify-between mb-1.5">
          <label className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Public Remarks</label>
          <span className={`text-xs tabular-nums ${pub.length > MAX_CHARS ? "text-destructive font-medium" : "text-muted-foreground"}`}>
            {pub.length}/{MAX_CHARS}
          </span>
        </div>
        {editing || !pub ? (
          <Textarea
            value={pub}
            onChange={(e) => setPub(e.target.value.slice(0, MAX_CHARS))}
            placeholder="Consumer-facing description highlighting lifestyle, neighbourhood, and key features..."
            rows={4}
            className="text-sm resize-none"
            onFocus={() => setEditing(true)}
          />
        ) : (
          <div
            onClick={() => setEditing(true)}
            className="p-3 rounded-lg bg-muted/30 border border-border/30 text-sm cursor-pointer hover:bg-muted/50 transition-colors"
          >
            {pub}
          </div>
        )}
      </div>

      {/* REALTOR Remarks */}
      <div>
        <div className="flex items-center justify-between mb-1.5">
          <label className="text-xs font-medium text-muted-foreground uppercase tracking-wide">REALTOR Remarks</label>
          <span className={`text-xs tabular-nums ${realtor.length > MAX_CHARS ? "text-destructive font-medium" : "text-muted-foreground"}`}>
            {realtor.length}/{MAX_CHARS}
          </span>
        </div>
        {editing || !realtor ? (
          <Textarea
            value={realtor}
            onChange={(e) => setRealtor(e.target.value.slice(0, MAX_CHARS))}
            placeholder="Agent-to-agent notes: showing instructions, lockbox, access, commission..."
            rows={3}
            className="text-sm resize-none"
            onFocus={() => setEditing(true)}
          />
        ) : (
          <div
            onClick={() => setEditing(true)}
            className="p-3 rounded-lg bg-muted/30 border border-border/30 text-sm cursor-pointer hover:bg-muted/50 transition-colors"
          >
            {realtor}
          </div>
        )}
      </div>

      {/* Save button */}
      {hasChanges && editing && (
        <div className="flex justify-end">
          <Button
            size="sm"
            onClick={handleSave}
            disabled={saving}
            className="gap-1.5 bg-brand hover:bg-brand/90"
          >
            {saving ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Save className="h-3.5 w-3.5" />}
            Save Remarks
          </Button>
        </div>
      )}

      {!pub && !realtor && !generating && (
        <p className="text-xs text-muted-foreground text-center py-2 italic">
          Click &quot;AI Generate&quot; to create MLS-ready descriptions from your listing data
        </p>
      )}
    </div>
  );
}
